format = """
$time\
$username\
$directory\
$git_branch\
$git_status\
$nodejs\
$golang\
$docker_context\
$line_break\
$character
"""

add_newline = false

# Show time (optional)
[time]
disabled = false
format = "[$time]($style) "

# Show username (optional)
[username]
show_always = true
style_user = "bold blue"
style_root = "bold red"

# Directory settings
[directory]
truncation_length = 3
truncate_to_repo = false
style = "bold cyan"

# Git branch & status
[git_branch]
symbol = "ğŸŒ± "
style = "bold purple"

[git_status]
style = "bold yellow"

# Node.js version
[nodejs]
symbol = "â¬¢ "

# Go version
[golang]
symbol = "ğŸ¹ "

# Docker context
[docker_context]
symbol = "ğŸ³ "

# New line before input
[line_break]

# The character before you type
[character]
success_symbol = "[âœ](bold green) "
error_symbol = "[âœ—](bold red) "
